version: "1.0"
stages:
  - "clone"
  - "build"
  - "metadata"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefresh-contrib/gitops-app-source-code"
    revision: '${{CF_REVISION}}'
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "kostiscodefresh/simple-web-app"
    working_directory: "${{clone}}"
    tags:
    - "latest"
    - '${{CF_SHORT_REVISION}}'
    dockerfile: "Dockerfile"
    stage: "build"
    registry: dockerhub  
  enrich-image:
    title: Add PR info
    type: image-enricher
    stage: "metadata"
    arguments:
      IMAGE:  docker.io/kostiscodefresh/simple-web-app:latest
      BRANCH: '${{CF_BRANCH}}'
      REPO: 'kostis-codefresh/simple-web-app'
      GIT_PROVIDER_NAME: github-1
  jira-issue-extractor:
    title: Enrich image with jira issues
    type: jira-issue-extractor
    stage: "metadata"
    fail_fast: false
    arguments:
      IMAGE: docker.io/kostiscodefresh/simple-web-app:latest
      JIRA_PROJECT_PREFIX: 'SAAS'
      MESSAGE: SAAS-8431
      JIRA_HOST: codefresh-io.atlassian.net
      JIRA_EMAIL: kostis@codefresh.io
      JIRA_API_TOKEN: '${{JIRA_TOKEN}}'
    
    


